/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js in most projects. It is committed here so
// TypeScript has the expected ambient types before the first dev-server run.

